# Documentation: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: git-gateway # Substitute "test-repo" to view editor locally at localhost:3000/admin/index.html
  branch: main
media_folder: public/media
public_folder: /media
site_url: https://edinburgh-indie-gamers.netlify.app/ # TODO: Update when domain is added
collections:
  - name: "posts-news"
    label: "News Posts"
    folder: "./content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "./content/pages"
    create: false
    fields: 
     - { label: "Title", name: "title", widget: "string" }
     - { label: "Body", name: "body", widget: "markdown"}
          